project:
  type: website
  output-dir: docs

website:
  title: "Peteria Rose Aerial"
  navbar:
    pinned: true
    collapse: true
    search: false
    left:
      - href: index.qmd
        text: Home
      - Bio.qmd
      - Gallery.qmd
      - Video.qmd
      - CV.qmd
      
format:
  html:
    theme: pulse
    toc: false
editor: visual

