---
title: "CV"
---

### PERFORMANCES

#### 2024

-   October, *Altitude* *Aerial* *Arts* *Showcase*, silks performer -- Frisco, TX
-   September, *Carolina* *Circus* *Festival*, Pro-show, silks performer -- Cary, NC
-   September, *Studio* *X* *Presents* *GRIMM* *Show*, silks performer -- Worcester, MA
-   June, *Texas* *Pole* *Showdown*, rope performer -- Frisco, TX
-   April, *Altitude* *Aerial* *Arts* *Showcase*, silks performer -- Frisco, TX

#### 2022

-   December, *Inflye* *Entertainment* *Nutcracker*, silks performer -- Hudson, MA
-   November, *Open* *Stage*s *Show* *at* *The* *Muse* *Cirque*, silks performer -- Brooklyn, NY
-   October, *Inflye* *Entertainment* *Showcase*, silks performer -- Hudson, MA
-   September, *Studio* *X* *Presents* *Diety* *Show*, silks performer -- Worcester, MA
-   June, *Hudson* *Fest*, silks performer -- Hudson, MA
-   June, *Inflye* *Entertainment* *Showcase*, silks performer - Hudson, MA

#### 2021

-   May, *Circus* *Complex* *Spring* *Showcase*, silks performer -- Newton, MA

#### 2020

-   October, *Studio* *X* *Presents* *Drive-thru* *Haunted* *House*, aerialist - East Brookfield, MA

### COMPETITIONS & AWARDS

-   2022 Florida Aerial Arts Championship, Semi-Pro Adult Silks, *1st* *place*
-   2022 VIVA Fest, Student Silks 30+, *1st* *place*
-   2021 Aerialympics Regionals, Advanced Adult Silks, *1st* *place*
-   2019 Aerialympics Regionals, Intermediate Adult Silks, *1st* *place*

### TRAINING

-   Paper Doll Militia Level 1 Teacher Training (Virtual)- June 2024
-   Altitude Pole and Aerial Arts, Sep 2023 -- present -- silks, rope, hoop, flexibility
-   Inflyte Entertainment, Aug 2021 to 2023 -- silks, hoop
-   Moody Street Circus, October 2023 - silks, hoop
-   Jenn Bruyer (Patreon, online), May 2020 to present - act creation and choreography
-   Sky High Studios, Jan 2018 to June 2020 -- silks, hoop, pole
